route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
    - smarthost: 'smtp.gmail.com:587'
      auth_username: 'your-from-email'
      auth_password: 'your-app-password-without-space'
      from: 'your-from-email'
      to: 'your-to-email'
      headers:
          subject: 'Prometheus Mail Alerts'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
    